# Inventaire statique TaskFlow
# Les VMs sont créées avec Multipass (voir ressources/setup-lab.md)
# Récupérer les IP : multipass list

[web]
taskflow-web1 ansible_host=10.213.166.64
taskflow-web2 ansible_host=10.213.166.166

[web:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/taskflow_lab

# Le control node lui-même, pour piloter Kubernetes (kubectl/k3d local)
[k8s_control]
localhost ansible_connection=local
